project:
  type: website
  output-dir: docs

website:
  title: "Sophillium"
  
  navbar:
    left:
      - text: 理念・洞察
        href: 01_index.qmd
      - text: 投資・市場
        href: 02_investment.qmd
      - text: 経済・経営
        href: 03_economy_Business.qmd
      - text: 作り方
        href: 11_create_website.qmd
      - icon: github
        href: https://github.com/NekoKaruni/Sophillium.git
      - icon: info-circle
        href: 12_Author.qmd

  sidebar:
    left:
    style: "docked"
    collapse-level: 1
    search: true
    contents:
    - section: "理念・洞察"
      contents: 
       - text: 概要 
         href: 01_index.qmd
    - section: "投資・市場"
      contents: 
       - text: 投資・市場 概要
         href: 02_investment.qmd
       - text: 詳細解説
         href: 02_investment_Summary.qmd
       - text: TOPIX
         href: TOPIX.qmd
    - section: "経済・経営"
      contents: 
       - text: 経済・経営 概要
         href: 03_economy_Business_Summary.qmd
       - text: マクロ経済学
         href: 03_MacroEconomics.qmd
       - text: 経営論
         href: 03_BusinessManagement.qmd

format: 
  html: 
    toc: true
    css: styles.css 
    margin:
      top: 0.5in
      bottom: 0.5in
      left: 0.5in
      right: 0.5in
editor: visual
