project:
  type: website
  output-dir: docs

website:
  title: "Sophillium"
  
  
  navbar:
    left:
      - href: 01_index.qmd
        text: 理念・洞察
      - href: 02_investment.qmd
        text: 投資・市場
      - href: 03_economy_Business.qmd
        text: 経済・経営
     
    right:
      - text: 作り方
        href: 11_create_website.qmd
      - icon: github
        href: https://github.com/NekoKaruni/Sophillium.git
      - icon: info-circle
        href: 12_Author.qmd

        
  sidebar:
    style: "floating"
    collapse: true
    contents:
      - section: "理念・洞察"
        contents:
          - href: 01_index.qmd
            text: 概要
      - section: "投資・市場"
        contents:
          - href: 02_investment.qmd
            text: 概要
          - href: 02_investment_Summary.qmd
            text: 詳細解説
      - section: "経済・経営"
        contents:
          - href: 03_economy_Business_Summary.qmd
            text: 概要
          - href: 03_MacroEconomics.qmd
            text: マクロ経済学
          - href: 03_BusinessManagement.qmd
            text: 経営論      
        
   
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
    navbar:
      fixed: top
      sticky: true
    sidebar:
      collapse: true
      float: true

editor: visual
